name: Build and deploy ASP.Net Core app to Azure Web App - sep490-backend-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache .NET dependencies
      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('SEP490-backend/**/*.csproj', 'SEP490-backend/**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Build and publish the application
      - name: Build and publish application
        run: dotnet publish SEP490-backend/SEP490-backend.csproj -c Release -o ./publish

      # Create .env file
      - name: Create .env file from GitHub Secrets
        run: echo '${{ secrets.DOTNET_ENV_FILE }}' > ./publish/.env

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sep490-backend-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D5D97BA4E12B4E2BB0A9A57A41B5944D }}
          package: ./publish
          startup-command: 'dotnet SEP490-backend.dll'

      # Clean up .env file
      - name: Clean up .env file
        run: rm ./publish/.env
