// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sep490_Backend.DTO.ResourceReqs;
using Sep490_Backend.Infra;

#nullable disable

namespace Sep490_Backend.Migrations
{
    [DbContext(typeof(BackendContext))]
    [Migration("20250315204604_add-iter3-database")]
    partial class additer3database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConstructPlanItemDetailMaterials", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("ConstructPlanItemDetailId")
                        .HasColumnType("integer");

                    b.HasKey("MaterialId", "ConstructPlanItemDetailId");

                    b.HasIndex("ConstructPlanItemDetailId");

                    b.ToTable("ConstructPlanItemDetailMaterials", (string)null);
                });

            modelBuilder.Entity("ConstructPlanItemDetailUsers", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceAllocationId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ResourceAllocationId");

                    b.HasIndex("ResourceAllocationId");

                    b.ToTable("ConstructPlanItemDetailUsers", (string)null);
                });

            modelBuilder.Entity("ConstructPlanItemDetailVehicles", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<int>("ConstructPlanItemDetailId")
                        .HasColumnType("integer");

                    b.HasKey("VehicleId", "ConstructPlanItemDetailId");

                    b.HasIndex("ConstructPlanItemDetailId");

                    b.ToTable("ConstructPlanItemDetailVehicles", (string)null);
                });

            modelBuilder.Entity("ConstructPlanItemQAs", b =>
                {
                    b.Property<string>("QAItemWorkCode")
                        .HasColumnType("text");

                    b.Property<int>("QAMemberId")
                        .HasColumnType("integer");

                    b.HasKey("QAItemWorkCode", "QAMemberId");

                    b.HasIndex("QAMemberId");

                    b.ToTable("ConstructPlanItemQAs", (string)null);
                });

            modelBuilder.Entity("ConstructionPlanReviewers", b =>
                {
                    b.Property<int>("ReviewedPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.HasKey("ReviewedPlanId", "ReviewerId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("ConstructionPlanReviewers", (string)null);
                });

            modelBuilder.Entity("ConstructionTeamPlanItems", b =>
                {
                    b.Property<int>("ConstructionTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("ConstructPlanItemWorkCode")
                        .HasColumnType("text");

                    b.HasKey("ConstructionTeamId", "ConstructPlanItemWorkCode");

                    b.HasIndex("ConstructPlanItemWorkCode");

                    b.ToTable("ConstructionTeamPlanItems", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LogType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LogType");

                    b.ToTable("ActionLogs", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructPlanItem", b =>
                {
                    b.Property<string>("WorkCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParentIndex")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlanQuantity")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PlanTotalPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<List<int>>("QA")
                        .HasColumnType("integer[]");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("WorkCode");

                    b.HasIndex("EndDate");

                    b.HasIndex("ParentIndex");

                    b.HasIndex("PlanId");

                    b.HasIndex("StartDate");

                    b.ToTable("ConstructPlanItems", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructPlanItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<string>("WorkCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlanItemId");

                    b.HasIndex("ResourceType");

                    b.HasIndex("WorkCode");

                    b.ToTable("ConstructPlanItemDetails", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<Dictionary<int, bool>>("Reviewer")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanName");

                    b.HasIndex("ProjectId");

                    b.ToTable("ConstructionPlans", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructionTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("TeamManager")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamManager")
                        .IsUnique();

                    b.HasIndex("TeamName");

                    b.ToTable("ConstructionTeams", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SignDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ContractDetail", b =>
                {
                    b.Property<string>("WorkCode")
                        .HasColumnType("text");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParentIndex")
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkCode");

                    b.HasIndex("ContractId");

                    b.HasIndex("ParentIndex");

                    b.ToTable("ContractDetails", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DirectorName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.ToTable("EmailTemplates", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachment")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Inventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("MadeIn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("RetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WholesalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ConstructType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicalReqs")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ProjectUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCreator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId");

                    b.ToTable("ProjectUsers", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ResourceAllocationReqs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FromProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<List<RequestDetails>>("ResourceAllocationDetails")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ToProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Creator");

                    b.HasIndex("FromProjectId");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("ToProjectId");

                    b.HasIndex("Updater");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("ResourceAllocationReqs", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ResourceMobilizationReqs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<List<RequestDetails>>("ResourceMobilizationDetails")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Creator");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.HasIndex("RequestDate");

                    b.HasIndex("Status");

                    b.HasIndex("Updater");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("ResourceMobilizationReqs", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.SiteSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<double>("BidWinProb")
                        .HasColumnType("double precision");

                    b.Property<int>("BiddingDecision")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("ConstructionRequirements")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<double>("DiscountRate")
                        .HasColumnType("double precision");

                    b.Property<string>("EquipmentRequirements")
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedExpenses")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("EstimatedProfits")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FinalProfit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("HumanResourceCapacity")
                        .HasColumnType("text");

                    b.Property<string>("ProfitAssessment")
                        .HasColumnType("text");

                    b.Property<decimal>("ProjectCost")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("RiskAssessment")
                        .HasColumnType("text");

                    b.Property<string>("SiteSurveyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SurveyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TenderPackagePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalBidPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("SiteSurveys", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructionTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerify")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionTeamId");

                    b.HasIndex("Deleted");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("Gender");

                    b.HasIndex("IsVerify");

                    b.HasIndex("Phone");

                    b.HasIndex("TeamId");

                    b.HasIndex("Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryOfManufacture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Creator")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Driver")
                        .HasColumnType("integer");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FuelTankVolume")
                        .HasColumnType("integer");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updater")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Driver")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("ConstructPlanItemDetailMaterials", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructPlanItemDetail", null)
                        .WithMany()
                        .HasForeignKey("ConstructPlanItemDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructPlanItemDetailMaterials_ConstructPlanItemDetails_ConstructPlanItemDetailId");

                    b.HasOne("Sep490_Backend.Infra.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructPlanItemDetailMaterials_Materials_MaterialId");
                });

            modelBuilder.Entity("ConstructPlanItemDetailUsers", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructPlanItemDetail", null)
                        .WithMany()
                        .HasForeignKey("ResourceAllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructPlanItemDetailUsers_ConstructPlanItemDetails_ResourceAllocationId");

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructPlanItemDetailUsers_Users_UserId");
                });

            modelBuilder.Entity("ConstructPlanItemDetailVehicles", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructPlanItemDetail", null)
                        .WithMany()
                        .HasForeignKey("ConstructPlanItemDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructPlanItemDetailVehicles_ConstructPlanItemDetails_ConstructPlanItemDetailId");

                    b.HasOne("Sep490_Backend.Infra.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructPlanItemDetailVehicles_Vehicles_VehicleId");
                });

            modelBuilder.Entity("ConstructPlanItemQAs", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructPlanItem", null)
                        .WithMany()
                        .HasForeignKey("QAItemWorkCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructPlanItemQAs_ConstructPlanItems_QAItemWorkCode");

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("QAMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructPlanItemQAs_Users_QAMemberId");
                });

            modelBuilder.Entity("ConstructionPlanReviewers", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructionPlan", null)
                        .WithMany()
                        .HasForeignKey("ReviewedPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructionPlanReviewers_ConstructionPlans_ReviewedPlanId");

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructionPlanReviewers_Users_ReviewerId");
                });

            modelBuilder.Entity("ConstructionTeamPlanItems", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructPlanItem", null)
                        .WithMany()
                        .HasForeignKey("ConstructPlanItemWorkCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructionTeamPlanItems_ConstructPlanItems_ConstructPlanItemWorkCode");

                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructionTeam", null)
                        .WithMany()
                        .HasForeignKey("ConstructionTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConstructionTeamPlanItems_ConstructionTeams_ConstructionTeamId");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructPlanItem", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructPlanItem", "ParentItem")
                        .WithMany("ChildItems")
                        .HasForeignKey("ParentIndex")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructionPlan", "ConstructionPlan")
                        .WithMany("ConstructPlanItems")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionPlan");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructPlanItemDetail", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructPlanItem", "ConstructPlanItem")
                        .WithMany("ConstructPlanItemDetails")
                        .HasForeignKey("PlanItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructPlanItem");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructionPlan", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.Project", "Project")
                        .WithMany("ConstructionPlans")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructionTeam", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.User", "Manager")
                        .WithOne("ManagedTeam")
                        .HasForeignKey("Sep490_Backend.Infra.Entities.ConstructionTeam", "TeamManager")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Contract", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.Project", "Project")
                        .WithMany("Contracts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ContractDetail", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.Contract", "Contract")
                        .WithMany("ContractDetails")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.ContractDetail", "ParentItem")
                        .WithMany("ChildItems")
                        .HasForeignKey("ParentIndex")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contract");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Project", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ProjectUser", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.RefreshToken", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ResourceAllocationReqs", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("Creator")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.Project", "FromProject")
                        .WithMany()
                        .HasForeignKey("FromProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ResourceAllocationReqs_FromProject");

                    b.HasOne("Sep490_Backend.Infra.Entities.Project", "ToProject")
                        .WithMany()
                        .HasForeignKey("ToProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ResourceAllocationReqs_ToProject");

                    b.HasOne("Sep490_Backend.Infra.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("Updater")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany("RequestedAllocations")
                        .HasForeignKey("UserId");

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany("ApprovedAllocations")
                        .HasForeignKey("UserId1");

                    b.Navigation("Approver");

                    b.Navigation("FromProject");

                    b.Navigation("Requester");

                    b.Navigation("ToProject");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ResourceMobilizationReqs", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("Creator")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.Project", "Project")
                        .WithMany("ResourceMobilizationReqs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("Updater")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany("RequestedMobilizations")
                        .HasForeignKey("UserId");

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany("ApprovedMobilizations")
                        .HasForeignKey("UserId1");

                    b.Navigation("Approver");

                    b.Navigation("Project");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.SiteSurvey", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.Project", "Project")
                        .WithMany("SiteSurveys")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany("ApprovedSurveys")
                        .HasForeignKey("UserId");

                    b.HasOne("Sep490_Backend.Infra.Entities.User", null)
                        .WithMany("ConductedSurveys")
                        .HasForeignKey("UserId1");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.User", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructionTeam", null)
                        .WithMany("Members")
                        .HasForeignKey("ConstructionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sep490_Backend.Infra.Entities.ConstructionTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Vehicle", b =>
                {
                    b.HasOne("Sep490_Backend.Infra.Entities.User", "User")
                        .WithOne("Vehicle")
                        .HasForeignKey("Sep490_Backend.Infra.Entities.Vehicle", "Driver")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructPlanItem", b =>
                {
                    b.Navigation("ChildItems");

                    b.Navigation("ConstructPlanItemDetails");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructionPlan", b =>
                {
                    b.Navigation("ConstructPlanItems");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ConstructionTeam", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Contract", b =>
                {
                    b.Navigation("ContractDetails");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.ContractDetail", b =>
                {
                    b.Navigation("ChildItems");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.Project", b =>
                {
                    b.Navigation("ConstructionPlans");

                    b.Navigation("Contracts");

                    b.Navigation("ProjectUsers");

                    b.Navigation("ResourceMobilizationReqs");

                    b.Navigation("SiteSurveys");
                });

            modelBuilder.Entity("Sep490_Backend.Infra.Entities.User", b =>
                {
                    b.Navigation("ApprovedAllocations");

                    b.Navigation("ApprovedMobilizations");

                    b.Navigation("ApprovedSurveys");

                    b.Navigation("ConductedSurveys");

                    b.Navigation("ManagedTeam")
                        .IsRequired();

                    b.Navigation("ProjectUsers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RequestedAllocations");

                    b.Navigation("RequestedMobilizations");

                    b.Navigation("Vehicle")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
